<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyTitle>ImageCare</AssemblyTitle>
        <AssemblyName>ImageCare</AssemblyName>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <Platforms>AnyCPU</Platforms>
        <ApplicationIcon>Assets\imagecare-logo.ico</ApplicationIcon>
        <Version>0.1.2</Version>

	    <OptimizationPreference>Speed</OptimizationPreference>
	    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
	    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\birdPoint.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\imagecare-logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\birdPoint.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.10" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0.6" />
    <PackageReference Include="Avalonia.Xaml.Interactions.DragAndDrop" Version="11.3.0.6" />
    <PackageReference Include="Avalonia.Xaml.Interactivity" Version="11.3.0.6" />
    <PackageReference Include="Deadpikle.AvaloniaProgressRing" Version="0.10.10" />
    <PackageReference Include="HanumanInstitute.LibMpv" Version="0.9.1" />
    <PackageReference Include="HanumanInstitute.LibMpv.Avalonia" Version="0.9.1" />
    <PackageReference Include="IconPacks.Avalonia.Lucide" Version="1.3.1" />
    <PackageReference Include="IconPacks.Avalonia.Material" Version="1.3.1" />
    <PackageReference Include="Irihi.Ursa" Version="1.14.1" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.14.1" />
    <PackageReference Include="LibMpv.Avalonia" Version="1.0.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="Mapsui.Avalonia" Version="5.0.2" />
    <PackageReference Include="PanAndZoom" Version="11.3.6" />
    <PackageReference Include="Prism.Avalonia" Version="9.0.537.11130" />
    <PackageReference Include="Prism.Commands.Ex" Version="0.1.9" />
    <PackageReference Include="Prism.DryIoc.Avalonia" Version="9.0.537.11130" />
    <PackageReference Include="Semi.Avalonia" Version="11.3.7.2" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImageCare.Core\ImageCare.Core.csproj" />
  </ItemGroup>
  
    <ItemGroup Condition="'$(RuntimeIdentifier)'=='win-x64' or '$(RuntimeIdentifier)'==''">
    <Content Include="win-x64\**">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup Condition="'$(RuntimeIdentifier)'=='win-x86'">
    <Content Include="win-x86\**">
      <Link>%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
