name: ImageCare Bild

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore the project
      run: dotnet restore
      
    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wpf-app
        path: ./publish

  deploy:
    needs: build
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: wpf-app
        path: ./publish

    - name: Zip the publish folder
      shell: pwsh
      run: |
        $publishPath = "./publish"
        $zipPath = "./ImageCareBin.zip"
        Compress-Archive -Path $publishPath -DestinationPath $zipPath -Force
        echo "Zipped folder: $zipPath"
        
    - name: Deploy to GitHub Releases
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.6
        release_name: Release v0.1.6
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ImageCareBin.zip
        asset_name: ImageCareBin.zip
        asset_content_type: application/zip