name: Deploy Windows Build

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: extract_version
      run: |
        $version = "${{ github.ref_name}}".Replace('v','')
        echo "VERSION=$version" >> $env:GITHUB_ENV
        echo "::set-output name=version::$version"
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Publish Application
      run: |
        dotnet publish ImageCare.UI.Avalonia/ImageCare.UI.Avalonia.csproj `
          -c Release `
          -p:Platform=AnyCPU `
          --self-contained true `
          -p:PublishReadyToRun=true `
          -p:DebugType=None `
          --output ./publish-output
    
    - name: Remove PDB files
      run: |
        Get-ChildItem -Path ./publish-output -Filter *.pdb -Recurse | Remove-Item -Force
    
    - name: Create Zip Archive
      run: |
        $zipName = "ImageCare-${{ env.VERSION }}-Windows.zip"
        Compress-Archive -Path "./publish-output/*" -DestinationPath $zipName
        echo "ZIP_PATH=$zipName" >> $env:GITHUB_ENV
    
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: ImageCare ${{ env.VERSION }}
        files: ${{ env.ZIP_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}